[control_plane]
eks-control-01.devopsverse.local ansible_host=10.0.1.100 ansible_user=ubuntu
aks-control-01.devopsverse.local ansible_host=10.1.1.100 ansible_user=azureuser
gke-control-01.devopsverse.local ansible_host=10.2.0.100 ansible_user=gcp_user

[gateways]
kong-ingress-01.devopsverse.local ansible_host=10.0.1.150 ansible_user=ubuntu
kong-ingress-02.devopsverse.local ansible_host=10.0.1.151 ansible_user=ubuntu

[kubernetes_nodes]
eks-node-01.devopsverse.local ansible_host=10.0.1.10 ansible_user=ubuntu
eks-node-02.devopsverse.local ansible_host=10.0.1.11 ansible_user=ubuntu
aks-node-01.devopsverse.local ansible_host=10.1.1.10 ansible_user=azureuser
gke-node-01.devopsverse.local ansible_host=10.2.0.10 ansible_user=gcp_user
